### ISSUE TITLE
Gumroad

### ISSUE THREAD

**Issue by Oxicid** [FujiSunflower/uv_rectangler#1]
Can you post it on Gumroad? (Gumroadに投稿できますか？)

**Comment by FujiSunflower** [comment]
I post it on BOOTH already.
BOOTH https://fujisunflower.booth.pm/items/1632106

**Comment by Oxicid** [comment]
I understood that you are selling on this site, but this site is Japanese and it will not be convenient for me to pay in it. Plus, on Gumroad, you'll expand your customer list.
